### ISSUE TITLE
Error on running with Py3

### ISSUE THREAD

**Issue by theSage21** [baverman/typetrainer#3]
On running `./run.py` I get the following error. Can you help?

```
Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    run()
  File "/home/manjaro/Desktop/typetrainer/typetrainer/run.py", line 4, in run
    from typetrainer.i18n import _
  File "/home/manjaro/Desktop/typetrainer/typetrainer/i18n.py", line 18, in <module>
    _ = lang.ugettext
AttributeError: 'NullTranslations' object has no attribute 'ugettext'
```

**Comment by baverman** [comment]
Sorry but typetrainer compatible with python2 only. You should install it and start as

```
python2 ./run.py
```

**Comment by theSage21** [comment]
Ah, my mistake. Should I try to port it to 3?

**Comment by baverman** [comment]
It will be not easy. Typetrainer uses gtk2 bindings and py3 works with gobject introspection. But it will be marvellous!

**Comment by theSage21** [comment]
Sigh, I will give it a shot anyways.
